name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restaurar dependencias
      run: dotnet restore
    - name: Compilar
      run: dotnet build --no-restore
    - name: Ejecutar pruebas
      run: dotnet test --no-build --verbosity normal
