//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAGINA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema; // Asegúrate de tener esto arriba

    public partial class Productos
    {
        public int ID_producto { get; set; }
        public string nombre_producto { get; set; }
        public int ID_categoria { get; set; }
        public decimal precio { get; set; }
        public int stock { get; set; }
        public int ID_proveedor { get; set; }
        public System.DateTime fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public string codigo_barras { get; set; }
    
        public virtual Categorias_Productos Categorias_Productos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public string ImagenQRUrl
        {
            get
            {
                return $"/CodigosQr/{codigo_barras}.png";
            }
        }
        [NotMapped]
        public string ImagenProductoUrl
        {
            get
            {
                return $"/ImagenesProductos/{codigo_barras}.png";
            }
        }

    }
}
